'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
'
Namespace WsFotosColetor
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="UploadSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Upload
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GravarFotoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObterFotoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExcluirFotoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Coletor.My.MySettings.Default.Coletor_WsFotosColetor_Upload
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GravarFotoCompleted As GravarFotoCompletedEventHandler
        
        '''<remarks/>
        Public Event ObterFotoCompleted As ObterFotoCompletedEventHandler
        
        '''<remarks/>
        Public Event ExcluirFotoCompleted As ExcluirFotoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GravarFoto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GravarFoto(ByVal idWorkflowFoto As String, ByVal autonumCntrBl As String, ByVal autonumPatio As String, ByVal autonumCsOp As String, ByVal bl As String, ByVal autonumCsrdx As String, ByVal autonumPatiordx As String, ByVal imagemBase64 As String) As String
            Dim results() As Object = Me.Invoke("GravarFoto", New Object() {idWorkflowFoto, autonumCntrBl, autonumPatio, autonumCsOp, bl, autonumCsrdx, autonumPatiordx, imagemBase64})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GravarFotoAsync(ByVal idWorkflowFoto As String, ByVal autonumCntrBl As String, ByVal autonumPatio As String, ByVal autonumCsOp As String, ByVal bl As String, ByVal autonumCsrdx As String, ByVal autonumPatiordx As String, ByVal imagemBase64 As String)
            Me.GravarFotoAsync(idWorkflowFoto, autonumCntrBl, autonumPatio, autonumCsOp, bl, autonumCsrdx, autonumPatiordx, imagemBase64, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GravarFotoAsync(ByVal idWorkflowFoto As String, ByVal autonumCntrBl As String, ByVal autonumPatio As String, ByVal autonumCsOp As String, ByVal bl As String, ByVal autonumCsrdx As String, ByVal autonumPatiordx As String, ByVal imagemBase64 As String, ByVal userState As Object)
            If (Me.GravarFotoOperationCompleted Is Nothing) Then
                Me.GravarFotoOperationCompleted = AddressOf Me.OnGravarFotoOperationCompleted
            End If
            Me.InvokeAsync("GravarFoto", New Object() {idWorkflowFoto, autonumCntrBl, autonumPatio, autonumCsOp, bl, autonumCsrdx, autonumPatiordx, imagemBase64}, Me.GravarFotoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGravarFotoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GravarFotoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GravarFotoCompleted(Me, New GravarFotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterFoto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterFoto(ByVal imagem_id As String) As String
            Dim results() As Object = Me.Invoke("ObterFoto", New Object() {imagem_id})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObterFotoAsync(ByVal imagem_id As String)
            Me.ObterFotoAsync(imagem_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObterFotoAsync(ByVal imagem_id As String, ByVal userState As Object)
            If (Me.ObterFotoOperationCompleted Is Nothing) Then
                Me.ObterFotoOperationCompleted = AddressOf Me.OnObterFotoOperationCompleted
            End If
            Me.InvokeAsync("ObterFoto", New Object() {imagem_id}, Me.ObterFotoOperationCompleted, userState)
        End Sub
        
        Private Sub OnObterFotoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObterFotoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObterFotoCompleted(Me, New ObterFotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExcluirFoto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExcluirFoto(ByVal imagem_id As String) As String
            Dim results() As Object = Me.Invoke("ExcluirFoto", New Object() {imagem_id})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExcluirFotoAsync(ByVal imagem_id As String)
            Me.ExcluirFotoAsync(imagem_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExcluirFotoAsync(ByVal imagem_id As String, ByVal userState As Object)
            If (Me.ExcluirFotoOperationCompleted Is Nothing) Then
                Me.ExcluirFotoOperationCompleted = AddressOf Me.OnExcluirFotoOperationCompleted
            End If
            Me.InvokeAsync("ExcluirFoto", New Object() {imagem_id}, Me.ExcluirFotoOperationCompleted, userState)
        End Sub
        
        Private Sub OnExcluirFotoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExcluirFotoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExcluirFotoCompleted(Me, New ExcluirFotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GravarFotoCompletedEventHandler(ByVal sender As Object, ByVal e As GravarFotoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GravarFotoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ObterFotoCompletedEventHandler(ByVal sender As Object, ByVal e As ObterFotoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObterFotoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ExcluirFotoCompletedEventHandler(ByVal sender As Object, ByVal e As ExcluirFotoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExcluirFotoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
