'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace loginMicroled
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="loginMicroled.CriptografiaSoap")>  _
    Public Interface CriptografiaSoap
        
        'CODEGEN: Generating message contract since element name nomeSistema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EncriptarTabela", ReplyAction:="*")>  _
        Function EncriptarTabela(ByVal request As loginMicroled.EncriptarTabelaRequest) As loginMicroled.EncriptarTabelaResponse
        
        'CODEGEN: Generating message contract since element name nomeSistema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DescriptarTabela", ReplyAction:="*")>  _
        Function DescriptarTabela(ByVal request As loginMicroled.DescriptarTabelaRequest) As loginMicroled.DescriptarTabelaResponse
        
        'CODEGEN: Generating message contract since element name nomeSistema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObterVersao", ReplyAction:="*")>  _
        Function ObterVersao(ByVal request As loginMicroled.ObterVersaoRequest) As loginMicroled.ObterVersaoResponse
        
        'CODEGEN: Generating message contract since element name nomeSistema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObterTabelaLogin", ReplyAction:="*")>  _
        Function ObterTabelaLogin(ByVal request As loginMicroled.ObterTabelaLoginRequest) As loginMicroled.ObterTabelaLoginResponse
        
        'CODEGEN: Generating message contract since element name tabela from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/usuLogOut", ReplyAction:="*")>  _
        Function usuLogOut(ByVal request As loginMicroled.usuLogOutRequest) As loginMicroled.usuLogOutResponse
        
        'CODEGEN: Generating message contract since element name tabela from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ValidarUsuario", ReplyAction:="*")>  _
        Function ValidarUsuario(ByVal request As loginMicroled.ValidarUsuarioRequest) As loginMicroled.ValidarUsuarioResponse
        
        'CODEGEN: Generating message contract since element name tabela from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ValidarUsuarioCPF", ReplyAction:="*")>  _
        Function ValidarUsuarioCPF(ByVal request As loginMicroled.ValidarUsuarioCPFRequest) As loginMicroled.ValidarUsuarioCPFResponse
        
        'CODEGEN: Generating message contract since element name novaSenha from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/alterarSenha", ReplyAction:="*")>  _
        Function alterarSenha(ByVal request As loginMicroled.alterarSenhaRequest) As loginMicroled.alterarSenhaResponse
        
        'CODEGEN: Generating message contract since element name schema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RetornaSenhaBD", ReplyAction:="*")>  _
        Function RetornaSenhaBD(ByVal request As loginMicroled.RetornaSenhaBDRequest) As loginMicroled.RetornaSenhaBDResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EncriptarTabelaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EncriptarTabela", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.EncriptarTabelaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.EncriptarTabelaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EncriptarTabelaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nomeSistema As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeSistema As String)
            MyBase.New
            Me.nomeSistema = nomeSistema
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EncriptarTabelaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EncriptarTabelaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.EncriptarTabelaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.EncriptarTabelaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EncriptarTabelaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EncriptarTabelaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncriptarTabelaResult As String)
            MyBase.New
            Me.EncriptarTabelaResult = EncriptarTabelaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DescriptarTabelaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DescriptarTabela", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.DescriptarTabelaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.DescriptarTabelaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DescriptarTabelaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nomeSistema As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeSistema As String)
            MyBase.New
            Me.nomeSistema = nomeSistema
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DescriptarTabelaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DescriptarTabelaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.DescriptarTabelaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.DescriptarTabelaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DescriptarTabelaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DescriptarTabelaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DescriptarTabelaResult As String)
            MyBase.New
            Me.DescriptarTabelaResult = DescriptarTabelaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObterVersaoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObterVersao", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.ObterVersaoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.ObterVersaoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObterVersaoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nomeSistema As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeSistema As String)
            MyBase.New
            Me.nomeSistema = nomeSistema
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObterVersaoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObterVersaoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.ObterVersaoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.ObterVersaoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObterVersaoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObterVersaoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObterVersaoResult As String)
            MyBase.New
            Me.ObterVersaoResult = ObterVersaoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObterTabelaLoginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObterTabelaLogin", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.ObterTabelaLoginRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.ObterTabelaLoginRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObterTabelaLoginRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nomeSistema As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeSistema As String)
            MyBase.New
            Me.nomeSistema = nomeSistema
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObterTabelaLoginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObterTabelaLoginResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.ObterTabelaLoginResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.ObterTabelaLoginResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObterTabelaLoginResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObterTabelaLoginResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObterTabelaLoginResult As String)
            MyBase.New
            Me.ObterTabelaLoginResult = ObterTabelaLoginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class usuLogOutRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="usuLogOut", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.usuLogOutRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.usuLogOutRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class usuLogOutRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public tabela As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public usuario As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tabela As String, ByVal usuario As String)
            MyBase.New
            Me.tabela = tabela
            Me.usuario = usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class usuLogOutResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="usuLogOutResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.usuLogOutResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.usuLogOutResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class usuLogOutResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuLogOutResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuLogOutResult As String)
            MyBase.New
            Me.usuLogOutResult = usuLogOutResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ValidarUsuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ValidarUsuario", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.ValidarUsuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.ValidarUsuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public tabela As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public senha As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tabela As String, ByVal usuario As String, ByVal senha As String)
            MyBase.New
            Me.tabela = tabela
            Me.usuario = usuario
            Me.senha = senha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ValidarUsuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ValidarUsuarioResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.ValidarUsuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.ValidarUsuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ValidarUsuarioResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ValidarUsuarioResult As String)
            MyBase.New
            Me.ValidarUsuarioResult = ValidarUsuarioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ValidarUsuarioCPFRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ValidarUsuarioCPF", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.ValidarUsuarioCPFRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.ValidarUsuarioCPFRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioCPFRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public tabela As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public cpf As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tabela As String, ByVal usuario As String, ByVal cpf As String)
            MyBase.New
            Me.tabela = tabela
            Me.usuario = usuario
            Me.cpf = cpf
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ValidarUsuarioCPFResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ValidarUsuarioCPFResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.ValidarUsuarioCPFResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.ValidarUsuarioCPFResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioCPFResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ValidarUsuarioCPFResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ValidarUsuarioCPFResult As String)
            MyBase.New
            Me.ValidarUsuarioCPFResult = ValidarUsuarioCPFResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class alterarSenhaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="alterarSenha", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.alterarSenhaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.alterarSenhaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class alterarSenhaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public novaSenha As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public tabela As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public login As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal novaSenha As String, ByVal tabela As String, ByVal login As String)
            MyBase.New
            Me.novaSenha = novaSenha
            Me.tabela = tabela
            Me.login = login
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class alterarSenhaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="alterarSenhaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.alterarSenhaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.alterarSenhaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class alterarSenhaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public alterarSenhaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal alterarSenhaResult As String)
            MyBase.New
            Me.alterarSenhaResult = alterarSenhaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RetornaSenhaBDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RetornaSenhaBD", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.RetornaSenhaBDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.RetornaSenhaBDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RetornaSenhaBDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public schema As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public baseHomologacao As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal schema As String, ByVal baseHomologacao As Boolean)
            MyBase.New
            Me.schema = schema
            Me.baseHomologacao = baseHomologacao
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RetornaSenhaBDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RetornaSenhaBDResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As loginMicroled.RetornaSenhaBDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As loginMicroled.RetornaSenhaBDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RetornaSenhaBDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RetornaSenhaBDResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetornaSenhaBDResult As String)
            MyBase.New
            Me.RetornaSenhaBDResult = RetornaSenhaBDResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CriptografiaSoapChannel
        Inherits loginMicroled.CriptografiaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CriptografiaSoapClient
        Inherits System.ServiceModel.ClientBase(Of loginMicroled.CriptografiaSoap)
        Implements loginMicroled.CriptografiaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_EncriptarTabela(ByVal request As loginMicroled.EncriptarTabelaRequest) As loginMicroled.EncriptarTabelaResponse Implements loginMicroled.CriptografiaSoap.EncriptarTabela
            Return MyBase.Channel.EncriptarTabela(request)
        End Function
        
        Public Function EncriptarTabela(ByVal nomeSistema As String) As String
            Dim inValue As loginMicroled.EncriptarTabelaRequest = New loginMicroled.EncriptarTabelaRequest()
            inValue.Body = New loginMicroled.EncriptarTabelaRequestBody()
            inValue.Body.nomeSistema = nomeSistema
            Dim retVal As loginMicroled.EncriptarTabelaResponse = CType(Me,loginMicroled.CriptografiaSoap).EncriptarTabela(inValue)
            Return retVal.Body.EncriptarTabelaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_DescriptarTabela(ByVal request As loginMicroled.DescriptarTabelaRequest) As loginMicroled.DescriptarTabelaResponse Implements loginMicroled.CriptografiaSoap.DescriptarTabela
            Return MyBase.Channel.DescriptarTabela(request)
        End Function
        
        Public Function DescriptarTabela(ByVal nomeSistema As String) As String
            Dim inValue As loginMicroled.DescriptarTabelaRequest = New loginMicroled.DescriptarTabelaRequest()
            inValue.Body = New loginMicroled.DescriptarTabelaRequestBody()
            inValue.Body.nomeSistema = nomeSistema
            Dim retVal As loginMicroled.DescriptarTabelaResponse = CType(Me,loginMicroled.CriptografiaSoap).DescriptarTabela(inValue)
            Return retVal.Body.DescriptarTabelaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_ObterVersao(ByVal request As loginMicroled.ObterVersaoRequest) As loginMicroled.ObterVersaoResponse Implements loginMicroled.CriptografiaSoap.ObterVersao
            Return MyBase.Channel.ObterVersao(request)
        End Function
        
        Public Function ObterVersao(ByVal nomeSistema As String) As String
            Dim inValue As loginMicroled.ObterVersaoRequest = New loginMicroled.ObterVersaoRequest()
            inValue.Body = New loginMicroled.ObterVersaoRequestBody()
            inValue.Body.nomeSistema = nomeSistema
            Dim retVal As loginMicroled.ObterVersaoResponse = CType(Me,loginMicroled.CriptografiaSoap).ObterVersao(inValue)
            Return retVal.Body.ObterVersaoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_ObterTabelaLogin(ByVal request As loginMicroled.ObterTabelaLoginRequest) As loginMicroled.ObterTabelaLoginResponse Implements loginMicroled.CriptografiaSoap.ObterTabelaLogin
            Return MyBase.Channel.ObterTabelaLogin(request)
        End Function
        
        Public Function ObterTabelaLogin(ByVal nomeSistema As String) As String
            Dim inValue As loginMicroled.ObterTabelaLoginRequest = New loginMicroled.ObterTabelaLoginRequest()
            inValue.Body = New loginMicroled.ObterTabelaLoginRequestBody()
            inValue.Body.nomeSistema = nomeSistema
            Dim retVal As loginMicroled.ObterTabelaLoginResponse = CType(Me,loginMicroled.CriptografiaSoap).ObterTabelaLogin(inValue)
            Return retVal.Body.ObterTabelaLoginResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_usuLogOut(ByVal request As loginMicroled.usuLogOutRequest) As loginMicroled.usuLogOutResponse Implements loginMicroled.CriptografiaSoap.usuLogOut
            Return MyBase.Channel.usuLogOut(request)
        End Function
        
        Public Function usuLogOut(ByVal tabela As String, ByVal usuario As String) As String
            Dim inValue As loginMicroled.usuLogOutRequest = New loginMicroled.usuLogOutRequest()
            inValue.Body = New loginMicroled.usuLogOutRequestBody()
            inValue.Body.tabela = tabela
            inValue.Body.usuario = usuario
            Dim retVal As loginMicroled.usuLogOutResponse = CType(Me,loginMicroled.CriptografiaSoap).usuLogOut(inValue)
            Return retVal.Body.usuLogOutResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_ValidarUsuario(ByVal request As loginMicroled.ValidarUsuarioRequest) As loginMicroled.ValidarUsuarioResponse Implements loginMicroled.CriptografiaSoap.ValidarUsuario
            Return MyBase.Channel.ValidarUsuario(request)
        End Function
        
        Public Function ValidarUsuario(ByVal tabela As String, ByVal usuario As String, ByVal senha As String) As String
            Dim inValue As loginMicroled.ValidarUsuarioRequest = New loginMicroled.ValidarUsuarioRequest()
            inValue.Body = New loginMicroled.ValidarUsuarioRequestBody()
            inValue.Body.tabela = tabela
            inValue.Body.usuario = usuario
            inValue.Body.senha = senha
            Dim retVal As loginMicroled.ValidarUsuarioResponse = CType(Me,loginMicroled.CriptografiaSoap).ValidarUsuario(inValue)
            Return retVal.Body.ValidarUsuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_ValidarUsuarioCPF(ByVal request As loginMicroled.ValidarUsuarioCPFRequest) As loginMicroled.ValidarUsuarioCPFResponse Implements loginMicroled.CriptografiaSoap.ValidarUsuarioCPF
            Return MyBase.Channel.ValidarUsuarioCPF(request)
        End Function
        
        Public Function ValidarUsuarioCPF(ByVal tabela As String, ByVal usuario As String, ByVal cpf As String) As String
            Dim inValue As loginMicroled.ValidarUsuarioCPFRequest = New loginMicroled.ValidarUsuarioCPFRequest()
            inValue.Body = New loginMicroled.ValidarUsuarioCPFRequestBody()
            inValue.Body.tabela = tabela
            inValue.Body.usuario = usuario
            inValue.Body.cpf = cpf
            Dim retVal As loginMicroled.ValidarUsuarioCPFResponse = CType(Me,loginMicroled.CriptografiaSoap).ValidarUsuarioCPF(inValue)
            Return retVal.Body.ValidarUsuarioCPFResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_alterarSenha(ByVal request As loginMicroled.alterarSenhaRequest) As loginMicroled.alterarSenhaResponse Implements loginMicroled.CriptografiaSoap.alterarSenha
            Return MyBase.Channel.alterarSenha(request)
        End Function
        
        Public Function alterarSenha(ByVal novaSenha As String, ByVal tabela As String, ByVal login As String) As String
            Dim inValue As loginMicroled.alterarSenhaRequest = New loginMicroled.alterarSenhaRequest()
            inValue.Body = New loginMicroled.alterarSenhaRequestBody()
            inValue.Body.novaSenha = novaSenha
            inValue.Body.tabela = tabela
            inValue.Body.login = login
            Dim retVal As loginMicroled.alterarSenhaResponse = CType(Me,loginMicroled.CriptografiaSoap).alterarSenha(inValue)
            Return retVal.Body.alterarSenhaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function loginMicroled_CriptografiaSoap_RetornaSenhaBD(ByVal request As loginMicroled.RetornaSenhaBDRequest) As loginMicroled.RetornaSenhaBDResponse Implements loginMicroled.CriptografiaSoap.RetornaSenhaBD
            Return MyBase.Channel.RetornaSenhaBD(request)
        End Function
        
        Public Function RetornaSenhaBD(ByVal schema As String, ByVal baseHomologacao As Boolean) As String
            Dim inValue As loginMicroled.RetornaSenhaBDRequest = New loginMicroled.RetornaSenhaBDRequest()
            inValue.Body = New loginMicroled.RetornaSenhaBDRequestBody()
            inValue.Body.schema = schema
            inValue.Body.baseHomologacao = baseHomologacao
            Dim retVal As loginMicroled.RetornaSenhaBDResponse = CType(Me,loginMicroled.CriptografiaSoap).RetornaSenhaBD(inValue)
            Return retVal.Body.RetornaSenhaBDResult
        End Function
    End Class
End Namespace
