'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebFormICNTR

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtSistema control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSistema As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAutonum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAutonum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCNTR4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNTR4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCNTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNTR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btFiltra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btFiltra As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTiPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTiPO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGWT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGWT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEscala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEscala As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIMO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEntrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntrada As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCATEG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCATEG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNavio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNavio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPosicionamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPosicionamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtYardAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYardAtual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRegime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCamera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCamera As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtYard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYard As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbMotivoPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMotivoPos As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbEmpilhadeira control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEmpilhadeira As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVeiculo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSalvar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSalvar0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSalvar0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btAvarias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAvarias As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSair As Global.System.Web.UI.WebControls.Button
End Class
