'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''cbConteiner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbConteiner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbLotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbLotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbItem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdatePanelNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelNovoItem As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblLote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelEmbalagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelEmbalagem As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cbEmbalagemNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEmbalagemNovoItem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtQtdeNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQtdeNovoItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtMercadoriaNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMercadoriaNovoItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVolumeNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolumeNovoItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtImportadorNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImportadorNovoItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoBrutoNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoBrutoNovoItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMarcaNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMarcaNovoItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIMONovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMONovoItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtONUNovoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtONUNovoItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSalvarNovoitem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarNovoitem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cbEmbalagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEmbalagem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtQtde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQtde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolume As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtImportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImportador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoBruto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoBruto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMarca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMarca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIMO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtONU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtONU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckAnvisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAnvisa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtTempAnvisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTempAnvisa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTempAnvisaMax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTempAnvisaMax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAnvisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnvisa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckHubPort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckHubPort As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckAvaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAvaria As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckAcrescimo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAcrescimo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckIDFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckIDFA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckDespachante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckDespachante As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtMarcante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMarcante As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtQtdeM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQtdeM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEtiquetas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEtiquetas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstMarcantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstMarcantes As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtTerminal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTerminal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDtInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDtInicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDtFim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDtFim As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDtFim0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDtFim0 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtQtdeM0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQtdeM0 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridDesovas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDesovas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnConfirma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnConfirma As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFecharConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFecharConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtQM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtIMOCAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtIMOCAP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtEMB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEMB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ModalPopupExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtender1 As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''btnFotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFotos As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSalvar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btLogOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btLogOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSair As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSair0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSair0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSalvar0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSalvar0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btRem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRem As Global.System.Web.UI.WebControls.Button
End Class
