'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace DesovaService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestBase", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Requests"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(DesovaService.RequestStop)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(DesovaService.RequestStart))>  _
    Partial Public Class RequestBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SortField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SortDirectionField As DesovaService.EnumeratorsSortDirection
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Page() As Integer
            Get
                Return Me.PageField
            End Get
            Set
                If (Me.PageField.Equals(value) <> true) Then
                    Me.PageField = value
                    Me.RaisePropertyChanged("Page")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sort() As String
            Get
                Return Me.SortField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SortField, value) <> true) Then
                    Me.SortField = value
                    Me.RaisePropertyChanged("Sort")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SortDirection() As DesovaService.EnumeratorsSortDirection
            Get
                Return Me.SortDirectionField
            End Get
            Set
                If (Me.SortDirectionField.Equals(value) <> true) Then
                    Me.SortDirectionField = value
                    Me.RaisePropertyChanged("SortDirection")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestStop", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Requests.MobileSe"& _ 
        "rvices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RequestStop
        Inherits DesovaService.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EndDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCameraField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTimelineField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EndDate() As System.Nullable(Of Date)
            Get
                Return Me.EndDateField
            End Get
            Set
                If (Me.EndDateField.Equals(value) <> true) Then
                    Me.EndDateField = value
                    Me.RaisePropertyChanged("EndDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCamera() As Integer
            Get
                Return Me.IdCameraField
            End Get
            Set
                If (Me.IdCameraField.Equals(value) <> true) Then
                    Me.IdCameraField = value
                    Me.RaisePropertyChanged("IdCamera")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTimeline() As Integer
            Get
                Return Me.IdTimelineField
            End Get
            Set
                If (Me.IdTimelineField.Equals(value) <> true) Then
                    Me.IdTimelineField = value
                    Me.RaisePropertyChanged("IdTimeline")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestStart", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Requests.MobileSe"& _ 
        "rvices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RequestStart
        Inherits DesovaService.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContainerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PositionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idCameraField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idOperationTypeField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Container() As String
            Get
                Return Me.ContainerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContainerField, value) <> true) Then
                    Me.ContainerField = value
                    Me.RaisePropertyChanged("Container")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Position() As Integer
            Get
                Return Me.PositionField
            End Get
            Set
                If (Me.PositionField.Equals(value) <> true) Then
                    Me.PositionField = value
                    Me.RaisePropertyChanged("Position")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idCamera() As Integer
            Get
                Return Me.idCameraField
            End Get
            Set
                If (Me.idCameraField.Equals(value) <> true) Then
                    Me.idCameraField = value
                    Me.RaisePropertyChanged("idCamera")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idOperationType() As Integer
            Get
                Return Me.idOperationTypeField
            End Get
            Set
                If (Me.idOperationTypeField.Equals(value) <> true) Then
                    Me.idOperationTypeField = value
                    Me.RaisePropertyChanged("idOperationType")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Enumerators.SortDirection", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Core")>  _
    Public Enum EnumeratorsSortDirection As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Ascending = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Descending = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseBase", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Responses"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(DesovaService.Response)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(DesovaService.Response1)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(DesovaService.ResponseStop)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(DesovaService.ResponseLoadInfo)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(DesovaService.ResponseStart))>  _
    Partial Public Class ResponseBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateTimeServerField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateTimeServer() As Date
            Get
                Return Me.DateTimeServerField
            End Get
            Set
                If (Me.DateTimeServerField.Equals(value) <> true) Then
                    Me.DateTimeServerField = value
                    Me.RaisePropertyChanged("DateTimeServer")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Response", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Responses.Operati"& _ 
        "onType"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Response
        Inherits DesovaService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descriptionOperationTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idOperationTypeField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descriptionOperationType() As String
            Get
                Return Me.descriptionOperationTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descriptionOperationTypeField, value) <> true) Then
                    Me.descriptionOperationTypeField = value
                    Me.RaisePropertyChanged("descriptionOperationType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idOperationType() As Integer
            Get
                Return Me.idOperationTypeField
            End Get
            Set
                If (Me.idOperationTypeField.Equals(value) <> true) Then
                    Me.idOperationTypeField = value
                    Me.RaisePropertyChanged("idOperationType")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Response", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Responses.Camera"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Response1
        Inherits DesovaService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descriptionCameraField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idCameraField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private loginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private passwdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private positionsField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private uriField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descriptionCamera() As String
            Get
                Return Me.descriptionCameraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descriptionCameraField, value) <> true) Then
                    Me.descriptionCameraField = value
                    Me.RaisePropertyChanged("descriptionCamera")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idCamera() As Integer
            Get
                Return Me.idCameraField
            End Get
            Set
                If (Me.idCameraField.Equals(value) <> true) Then
                    Me.idCameraField = value
                    Me.RaisePropertyChanged("idCamera")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property login() As String
            Get
                Return Me.loginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.loginField, value) <> true) Then
                    Me.loginField = value
                    Me.RaisePropertyChanged("login")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property passwd() As String
            Get
                Return Me.passwdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.passwdField, value) <> true) Then
                    Me.passwdField = value
                    Me.RaisePropertyChanged("passwd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property positions() As System.Nullable(Of Decimal)
            Get
                Return Me.positionsField
            End Get
            Set
                If (Me.positionsField.Equals(value) <> true) Then
                    Me.positionsField = value
                    Me.RaisePropertyChanged("positions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property uri() As String
            Get
                Return Me.uriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.uriField, value) <> true) Then
                    Me.uriField = value
                    Me.RaisePropertyChanged("uri")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseStop", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Responses.MobileS"& _ 
        "ervices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResponseStop
        Inherits DesovaService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private successField As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                If (Me.successField.Equals(value) <> true) Then
                    Me.successField = value
                    Me.RaisePropertyChanged("success")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseLoadInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Responses.MobileS"& _ 
        "ervices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResponseLoadInfo
        Inherits DesovaService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CamerasField() As DesovaService.Response1
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationTypesField() As DesovaService.Response
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cameras() As DesovaService.Response1()
            Get
                Return Me.CamerasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CamerasField, value) <> true) Then
                    Me.CamerasField = value
                    Me.RaisePropertyChanged("Cameras")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperationTypes() As DesovaService.Response()
            Get
                Return Me.OperationTypesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperationTypesField, value) <> true) Then
                    Me.OperationTypesField = value
                    Me.RaisePropertyChanged("OperationTypes")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseStart", [Namespace]:="http://schemas.datacontract.org/2004/07/Desova.Shared.Model.DTO.Responses.MobileS"& _ 
        "ervices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResponseStart
        Inherits DesovaService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idTimelineField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idTimeline() As Integer
            Get
                Return Me.idTimelineField
            End Get
            Set
                If (Me.idTimelineField.Equals(value) <> true) Then
                    Me.idTimelineField = value
                    Me.RaisePropertyChanged("idTimeline")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="DesovaService.IDesovaService")>  _
    Public Interface IDesovaService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDesovaService/StartRecording", ReplyAction:="http://tempuri.org/IDesovaService/StartRecordingResponse")>  _
        Function StartRecording(ByVal request As DesovaService.RequestStart) As DesovaService.ResponseStart
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IDesovaService/StartRecording", ReplyAction:="http://tempuri.org/IDesovaService/StartRecordingResponse")>  _
        Function BeginStartRecording(ByVal request As DesovaService.RequestStart, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndStartRecording(ByVal result As System.IAsyncResult) As DesovaService.ResponseStart
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDesovaService/StopRecording", ReplyAction:="http://tempuri.org/IDesovaService/StopRecordingResponse")>  _
        Function StopRecording(ByVal request As DesovaService.RequestStop) As DesovaService.ResponseStop
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IDesovaService/StopRecording", ReplyAction:="http://tempuri.org/IDesovaService/StopRecordingResponse")>  _
        Function BeginStopRecording(ByVal request As DesovaService.RequestStop, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndStopRecording(ByVal result As System.IAsyncResult) As DesovaService.ResponseStop
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDesovaService/LoadInfo", ReplyAction:="http://tempuri.org/IDesovaService/LoadInfoResponse")>  _
        Function LoadInfo() As DesovaService.ResponseLoadInfo
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IDesovaService/LoadInfo", ReplyAction:="http://tempuri.org/IDesovaService/LoadInfoResponse")>  _
        Function BeginLoadInfo(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndLoadInfo(ByVal result As System.IAsyncResult) As DesovaService.ResponseLoadInfo
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IDesovaServiceChannel
        Inherits DesovaService.IDesovaService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class StartRecordingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As DesovaService.ResponseStart
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DesovaService.ResponseStart)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class StopRecordingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As DesovaService.ResponseStop
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DesovaService.ResponseStop)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LoadInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As DesovaService.ResponseLoadInfo
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DesovaService.ResponseLoadInfo)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DesovaServiceClient
        Inherits System.ServiceModel.ClientBase(Of DesovaService.IDesovaService)
        Implements DesovaService.IDesovaService
        
        Private onBeginStartRecordingDelegate As BeginOperationDelegate
        
        Private onEndStartRecordingDelegate As EndOperationDelegate
        
        Private onStartRecordingCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginStopRecordingDelegate As BeginOperationDelegate
        
        Private onEndStopRecordingDelegate As EndOperationDelegate
        
        Private onStopRecordingCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginLoadInfoDelegate As BeginOperationDelegate
        
        Private onEndLoadInfoDelegate As EndOperationDelegate
        
        Private onLoadInfoCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event StartRecordingCompleted As System.EventHandler(Of StartRecordingCompletedEventArgs)
        
        Public Event StopRecordingCompleted As System.EventHandler(Of StopRecordingCompletedEventArgs)
        
        Public Event LoadInfoCompleted As System.EventHandler(Of LoadInfoCompletedEventArgs)
        
        Public Function StartRecording(ByVal request As DesovaService.RequestStart) As DesovaService.ResponseStart Implements DesovaService.IDesovaService.StartRecording
            Return MyBase.Channel.StartRecording(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginStartRecording(ByVal request As DesovaService.RequestStart, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements DesovaService.IDesovaService.BeginStartRecording
            Return MyBase.Channel.BeginStartRecording(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndStartRecording(ByVal result As System.IAsyncResult) As DesovaService.ResponseStart Implements DesovaService.IDesovaService.EndStartRecording
            Return MyBase.Channel.EndStartRecording(result)
        End Function
        
        Private Function OnBeginStartRecording(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim request As DesovaService.RequestStart = CType(inValues(0),DesovaService.RequestStart)
            Return Me.BeginStartRecording(request, callback, asyncState)
        End Function
        
        Private Function OnEndStartRecording(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As DesovaService.ResponseStart = Me.EndStartRecording(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnStartRecordingCompleted(ByVal state As Object)
            If (Not (Me.StartRecordingCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent StartRecordingCompleted(Me, New StartRecordingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub StartRecordingAsync(ByVal request As DesovaService.RequestStart)
            Me.StartRecordingAsync(request, Nothing)
        End Sub
        
        Public Overloads Sub StartRecordingAsync(ByVal request As DesovaService.RequestStart, ByVal userState As Object)
            If (Me.onBeginStartRecordingDelegate Is Nothing) Then
                Me.onBeginStartRecordingDelegate = AddressOf Me.OnBeginStartRecording
            End If
            If (Me.onEndStartRecordingDelegate Is Nothing) Then
                Me.onEndStartRecordingDelegate = AddressOf Me.OnEndStartRecording
            End If
            If (Me.onStartRecordingCompletedDelegate Is Nothing) Then
                Me.onStartRecordingCompletedDelegate = AddressOf Me.OnStartRecordingCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginStartRecordingDelegate, New Object() {request}, Me.onEndStartRecordingDelegate, Me.onStartRecordingCompletedDelegate, userState)
        End Sub
        
        Public Function StopRecording(ByVal request As DesovaService.RequestStop) As DesovaService.ResponseStop Implements DesovaService.IDesovaService.StopRecording
            Return MyBase.Channel.StopRecording(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginStopRecording(ByVal request As DesovaService.RequestStop, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements DesovaService.IDesovaService.BeginStopRecording
            Return MyBase.Channel.BeginStopRecording(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndStopRecording(ByVal result As System.IAsyncResult) As DesovaService.ResponseStop Implements DesovaService.IDesovaService.EndStopRecording
            Return MyBase.Channel.EndStopRecording(result)
        End Function
        
        Private Function OnBeginStopRecording(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim request As DesovaService.RequestStop = CType(inValues(0),DesovaService.RequestStop)
            Return Me.BeginStopRecording(request, callback, asyncState)
        End Function
        
        Private Function OnEndStopRecording(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As DesovaService.ResponseStop = Me.EndStopRecording(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnStopRecordingCompleted(ByVal state As Object)
            If (Not (Me.StopRecordingCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent StopRecordingCompleted(Me, New StopRecordingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub StopRecordingAsync(ByVal request As DesovaService.RequestStop)
            Me.StopRecordingAsync(request, Nothing)
        End Sub
        
        Public Overloads Sub StopRecordingAsync(ByVal request As DesovaService.RequestStop, ByVal userState As Object)
            If (Me.onBeginStopRecordingDelegate Is Nothing) Then
                Me.onBeginStopRecordingDelegate = AddressOf Me.OnBeginStopRecording
            End If
            If (Me.onEndStopRecordingDelegate Is Nothing) Then
                Me.onEndStopRecordingDelegate = AddressOf Me.OnEndStopRecording
            End If
            If (Me.onStopRecordingCompletedDelegate Is Nothing) Then
                Me.onStopRecordingCompletedDelegate = AddressOf Me.OnStopRecordingCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginStopRecordingDelegate, New Object() {request}, Me.onEndStopRecordingDelegate, Me.onStopRecordingCompletedDelegate, userState)
        End Sub
        
        Public Function LoadInfo() As DesovaService.ResponseLoadInfo Implements DesovaService.IDesovaService.LoadInfo
            Return MyBase.Channel.LoadInfo
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginLoadInfo(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements DesovaService.IDesovaService.BeginLoadInfo
            Return MyBase.Channel.BeginLoadInfo(callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndLoadInfo(ByVal result As System.IAsyncResult) As DesovaService.ResponseLoadInfo Implements DesovaService.IDesovaService.EndLoadInfo
            Return MyBase.Channel.EndLoadInfo(result)
        End Function
        
        Private Function OnBeginLoadInfo(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginLoadInfo(callback, asyncState)
        End Function
        
        Private Function OnEndLoadInfo(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As DesovaService.ResponseLoadInfo = Me.EndLoadInfo(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnLoadInfoCompleted(ByVal state As Object)
            If (Not (Me.LoadInfoCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent LoadInfoCompleted(Me, New LoadInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub LoadInfoAsync()
            Me.LoadInfoAsync(Nothing)
        End Sub
        
        Public Overloads Sub LoadInfoAsync(ByVal userState As Object)
            If (Me.onBeginLoadInfoDelegate Is Nothing) Then
                Me.onBeginLoadInfoDelegate = AddressOf Me.OnBeginLoadInfo
            End If
            If (Me.onEndLoadInfoDelegate Is Nothing) Then
                Me.onEndLoadInfoDelegate = AddressOf Me.OnEndLoadInfo
            End If
            If (Me.onLoadInfoCompletedDelegate Is Nothing) Then
                Me.onLoadInfoCompletedDelegate = AddressOf Me.OnLoadInfoCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginLoadInfoDelegate, Nothing, Me.onEndLoadInfoDelegate, Me.onLoadInfoCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
