'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TalieDescargaRegistro
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblCarregando control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarregando As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTalie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTalie As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBStatusTalie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBStatusTalie As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtFim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFim As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRegistro As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnBuscarRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarRegistro As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtPlaca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPlaca As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnRetornarDados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetornarDados As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtReserva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtReserva As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCliente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DC_Conferente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DC_Conferente As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DC_Equipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DC_Equipe As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DC_Operacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DC_Operacao As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''BtObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtObservacao As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtCancelar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtGravar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtMc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtMc As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtExcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtExcluir As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtFinalizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtFinalizar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtObservacao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnFecharObs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFecharObs As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblCodigoBooking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoBooking As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblCodigoGate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoGate As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblCodigoRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoRegistro As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblCodigoReserva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoReserva As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblCodigoUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoUsuario As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblCodigoPatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoPatio As Global.System.Web.UI.WebControls.HiddenField
End Class
